version: '3.8'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd1
    command: >
      etcd --name etcd1
           --advertise-client-urls http://etcd1:2379
           --listen-client-urls http://0.0.0.0:2379
           --listen-peer-urls http://0.0.0.0:2380
           --initial-advertise-peer-urls http://etcd1:2380
           --initial-cluster-token pg-etcd-cluster
           --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
           --initial-cluster-state new
           --enable-v2=true
    networks:
      - pg-net
    ports:
      - "2379:2379"
      - "2380:2380"

  etcd2:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd2
    command: >
      etcd --name etcd2
           --advertise-client-urls http://etcd2:2379
           --listen-client-urls http://0.0.0.0:2379
           --listen-peer-urls http://0.0.0.0:2380
           --initial-advertise-peer-urls http://etcd2:2380
           --initial-cluster-token pg-etcd-cluster
           --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
           --initial-cluster-state new
           --enable-v2=true
    networks:
      - pg-net

  etcd3:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd3
    command: >
      etcd --name etcd3
           --advertise-client-urls http://etcd3:2379
           --listen-client-urls http://0.0.0.0:2379
           --listen-peer-urls http://0.0.0.0:2380
           --initial-advertise-peer-urls http://etcd3:2380
           --initial-cluster-token pg-etcd-cluster
           --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
           --initial-cluster-state new
           --enable-v2=true
    networks:
      - pg-net

  spilo1:
    image: my-spilo-image:14.0
    container_name: spilo1
    hostname: spilo1
    environment:
      - SCOPE=demo-cluster
      - ETCD_HOSTS=etcd1:2379,etcd2:2379,etcd3:2379
      - PATRONI_ETCD_API_VERSION=v2
      - PGPASSWORD_SUPERUSER=postgres
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=spilo1:8008
    networks:
      - pg-net
    ports:
      - "5433:5432"
      - "8008:8008"
    volumes:
      - spilo_data1:/home/postgres/pgroot

  spilo2:
    image: my-spilo-image:14.0
    container_name: spilo2
    hostname: spilo2
    environment:
      - SCOPE=demo-cluster
      - ETCD_HOSTS=etcd1:2379,etcd2:2379,etcd3:2379
      - PATRONI_ETCD_API_VERSION=v2
      - PGPASSWORD_SUPERUSER=postgres
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=spilo2:8008
    networks:
      - pg-net
    ports:
      - "5434:5432"
      - "8018:8008"
    volumes:
      - spilo_data2:/home/postgres/pgroot

  spilo3:
    image: my-spilo-image:14.0
    container_name: spilo3
    hostname: spilo3
    environment:
      - SCOPE=demo-cluster
      - ETCD_HOSTS=etcd1:2379,etcd2:2379,etcd3:2379
      - PATRONI_ETCD_API_VERSION=v2
      - PGPASSWORD_SUPERUSER=postgres
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=spilo3:8008
    networks:
      - pg-net
    ports:
      - "5435:5432"
      - "8028:8008"
    volumes:
      - spilo_data3:/home/postgres/pgroot

volumes:
  spilo_data1:
  spilo_data2:
  spilo_data3:

networks:
  pg-net:
    driver: bridge
